services:
    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /application
      networks:
          - internal
      volumes:
        - ./../:/application
        - ./sourcefiles/nginx:/etc/nginx/conf.d
#        - ./sourcefiles/nginx/logs:/var/log/nginx
      ports:
        - "${NGINX_PORT}:80"

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm

      working_dir: /application
      environment:
        - PHP_WORKER_INSTALL_BCMATH=true
      volumes:
          - ./../:/application
          - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      networks:
        - internal
    mysql:
      image: mysql:8.0
      container_name: ${PROJECT_NAME}-mysql
      restart: always
      env_file:
        - .env
      environment:
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - '${DB_PORT:-3306}:3306'
      networks:
        - internal

    mailpit:
        image: axllent/mailpit
        container_name: ${PROJECT_NAME}-mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - internal

    redis:
        image: redis:7.0.12
        container_name: ${PROJECT_NAME}-redis
        ports:
            - "6379:6379"
        networks:
            - internal

volumes:
    mysql-data:
        driver: local
networks:
    internal:
        driver: bridge
